version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=formation
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - formationdb:/var/lib/mysql

  spring_app:
    image: nihelriahi/formation:latest
    container_name: formationdevops
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/formation?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8081:8081
    depends_on:
      - mysqldb

volumes:
  formationdb:
