version: "2"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=formation
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - formation:/var/lib/mysql

  spring_app:
    image: nihelriahi/spring
    container_name: formationdevops
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/formation?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

volumes:
  formation:
